### PR TITLE
update nervos icons

### PR DESCRIPTION
**Pull request by katat**

### CODE REVIEW

**Comment by ApolloUnicorn** [comment]
This should target `develop` not `master`

**Comment by katat** [comment]
Updated. Please have a check once you are available. Thanks @ApolloUnicorn

**Comment by ApolloUnicorn** [comment]
@katat the updated logo is not appearing correctly. Can you please send me the original image file (whatever you are using to generate the gif)?
preview-chat-image

**Comment by katat** [comment]
@ApolloUnicorn 
Here is the 16x16 png file I used to convert the gif file.
nervos_N

**Comment by ApolloUnicorn** [comment]
Closing in favor of https://github.com/obsidiansystems/ledger-app-nervos/pull/205

**Pull request closed without merging**
